# Common config
max_secondary:
    val: 16
    desc: The maximum number of secondary processes
prompt:
    val: "spp > "
    desc: Command prompt
topo_size:
    val: 60%
    desc: Percentage or ratio of topo

# Secondary
sec_mem:
    val: -m 512
    desc: Mem size
sec_base_lcore:
    val: 1
    desc: Shared lcore among secondaries
sec_nfv_nof_lcores:
    val: 1
    desc: Default num of lcores for workers of spp_nfv
sec_vf_nof_lcores:
    val: 3
    desc: Default num of lcores for workers of spp_vf
sec_mirror_nof_lcores:
    val: 2
    desc: Default num of lcores for workers of spp_mirror
sec_pcap_nof_lcores:
    val: 2
    desc: Default num of lcores for workers of spp_pcap
sec_vhost_cli:
    val: ""
    desc: Vhost client mode, activated if set any of values
sec_pcap_port:
    val: "phy:0"
    desc: Default captured port
